---
collections:
  - name: fedora.linux_system_roles
    version: ">=1.21.0"
  - name: community.general
    version: ">=11.4.0"
  - name: infra.controller_configuration
    version: ">=2.6.0"
  - name: awx.awx
    version: ">=23.0.0"
  - name: infra.leapp
    version: 1.6.1

roles:
  - src: https://github.com/heatmiser/ansible-leapp.git
    scm: git
    version: 2024-01-07.01
    name: infra.leapp

  - src: https://github.com/heatmiser/infra.convert2rhel.git
    scm: git
    version: dev-2024-09-09.01
    name: infra.convert2rhel
...
