---
- name: Remediate
  hosts: "{{ dynamic_inventory_group | default(omit) }}"
  strategy: ansible.builtin.free
  gather_facts: true
  become: true
  force_handlers: true
  vars:
    leapp_include_delay: false

  tasks:
    - name: Include randomized delay before beginning remediation
      ansible.builtin.command: |
        python3 -c 'import time;import random;zzzzz=random.uniform(15.0,60.0);time.sleep(zzzzz);print(zzzzz)'
      delegate_to: localhost
      connection: local
      when: leapp_include_delay

    - name: Ensure vdo package is installed for Leapp checks
      ansible.builtin.dnf:
        name: vdo
        state: present

    - name: Automatically answer check_vdo prompt in Leapp answerfile
      ansible.builtin.command:
        cmd: leapp answer --section check_vdo.confirm=True
      changed_when: false

    # RHEL 7 -> RHEL 8 Remediation
    - name: "Remediate RHEL 7 systems preparing for RHEL 8 upgrade"
      ansible.builtin.include_tasks: remediate_rhel7.yml
      when: ansible_distribution_major_version | int == 7

    # RHEL 8 -> RHEL 9 Remediation
    - name: "Remediate RHEL 8 systems preparing for RHEL 9 upgrade"
      ansible.builtin.include_tasks: remediate_rhel8.yml
      when: ansible_distribution_major_version | int == 8

    # Fix Inhibitor 1: Update OS packages from 8.8 to 8.10
    - name: Update all system packages to RHEL 8.10
      ansible.builtin.dnf:
        name: "*"
        state: latest
        update_cache: true
      when: ansible_distribution_version is version('8.10', '<')

    - name: Reboot nodes to load 8.10 kernel
      ansible.builtin.reboot:
        reboot_timeout: 3600
      when: ansible_distribution_version is version('8.10', '<')

    # Fix Inhibitor 2: Allow RHEL 9.2 target version
    - name: Enable unsupported leapp upgrade path (RHEL 9.2)
      ansible.builtin.lineinfile:
        path: /etc/environment
        line: "LEAPP_UNSUPPORTED=1"
        state: present

  handlers:
    - name: "Restart sshd"
      ansible.builtin.service:
        name: sshd
        state: restarted

    - name: "Restart firewalld"
      ansible.builtin.service:
        name: firewalld
        state: restarted
...
