---
- name: Leapp Pre-Upgrade Analysis
  hosts: "{{ dynamic_inventory_group | default(omit) }}"
  strategy: ansible.builtin.free
  gather_facts: true
  become: true
  force_handlers: true
  vars_files:
    - "{{ playbook_dir }}/leapp_vars_810_92.yml"
  vars:
    leapp_include_delay: false
    leapp_release: "8.10"

  pre_tasks:
    - name: Register output of 'yum repolist'
      ansible.builtin.shell: |
        set -o pipefail
        yum repolist
      args:
        executable: /bin/bash
      register: yum_repolist
      changed_when: yum_repolist.rc != 0

    - name: Enable RHEL 8 AppStream and BaseOS repos (RHSM)
      ansible.builtin.rhsm_repository:
        name:
          - rhel-8-for-x86_64-baseos-rpms
          - rhel-8-for-x86_64-appstream-rpms
        state: enabled
      when:
        - ansible_distribution_major_version | int == 8
        - "'rhui' not in yum_repolist.stdout"

    - name: Enable RHUI RHEL 8 repos (AWS EC2 / RHUI)
      ansible.builtin.command: >
        dnf config-manager --set-enabled rhel-8-for-x86_64-appstream-rhui-rpms rhel-8-for-x86_64-baseos-rhui-rpms
      when:
        - ansible_distribution_major_version | int == 8
        - "'rhui' in yum_repolist.stdout"
      changed_when: false

    - name: Set fact for RHUI RHEL extras repo name when EC2 and utilizing RHUI
      ansible.builtin.set_fact:
        analysis_repos_el7: "rhel-7-server-rhui-extras-rpms"
      when:
        - ansible_system_vendor in ["Amazon EC2", "Xen"]
        - ansible_product_uuid | regex_search('^ec2|^EC2')
        - "'rhui' in yum_repolist.stdout"
        - ansible_distribution_major_version | int == 7

    - name: Set delay time via gather_facts
      ansible.builtin.set_fact:
        node_delay_time: "{{ inventory_hostname | regex_replace('^\\D+|\\..*', '') | int * 30 }}"
      when: leapp_include_delay

    - name: Include delay before starting analysis
      ansible.builtin.command: |
        python3 -c 'import time;time.sleep({{ node_delay_time }})'
      delegate_to: localhost
      connection: local
      when: leapp_include_delay

  tasks:
    - name: Execute Leapp Analysis Role
      ansible.builtin.include_role:
        name: infra.leapp.analysis
...
